services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: pi
      POSTGRES_USER: pi
      POSTGRES_PASSWORD: henk
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pi"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pi
      - SPRING_DATASOURCE_USERNAME=pi
      - SPRING_DATASOURCE_PASSWORD=henk
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_READONLY_URL=jdbc:postgresql://db:5432/pi
      - SPRING_DATASOURCE_READONLY_USERNAME=pi
      - SPRING_DATASOURCE_READONLY_PASSWORD=henk
      - SPRING_DATASOURCE_READONLY_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_URL=jdbc:postgresql://db:5432/pi
      - SPRING_FLYWAY_USER=pi
      - SPRING_FLYWAY_PASSWORD=henk
      - SPRING_FLYWAY_LOCATIONS=classpath:db/migration
    depends_on:
      - db
