name: Docker

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-jekyll-blog:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (contains(github.event.commits[0].modified, 'blog/') || contains(github.event.commits[0].added, 'blog/') || contains(github.event.commits[0].removed, 'blog/')) || (github.event_name == 'pull_request' && contains(github.event.pull_request.files, 'blog/'))
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Common steps
        id: common-steps
        uses: ./.github/actions/common-steps
        with:
          context: ./blog
          image_name: ${{ env.IMAGE_NAME }}-blog
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug tags output
        run: |
          echo "Tags: ${{ steps.common-steps.outputs.tags }}"

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./blog
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.common-steps.outputs.tags }}
          platforms: linux/arm64,linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.common-steps.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

  build-portfolio:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Debug GitHub Event Context
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Commits: ${{ toJson(github.event.commits) }}"
          echo "Pull Request Files: ${{ toJson(github.event.pull_request.changed_files) }}"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get list of modified files in PR
        id: get-modified-files
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
        
          # Fetching the modified files using GitHub API
          MODIFIED_FILES=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/files" | \
            jq -r '.[] | select(.filename | startswith("portfolio/")) | .filename')
        
          echo "Modified files: $MODIFIED_FILES"
          echo "modified_files=$MODIFIED_FILES" >> $GITHUB_ENV
          
      - name: Common steps
        id: common-steps
        uses: ./.github/actions/common-steps
        with:
          context: ./portfolio
          image_name: ${{ env.IMAGE_NAME }}-portfolio
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

      - name: Build and push Docker image
        if: contains(env.modified_files, 'portfolio/')
        id: build-and-push
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./portfolio
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.common-steps.outputs.tags }}
          platforms: linux/arm64,linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.common-steps.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

  build-api:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (contains(github.event.commits[0].modified, 'api/') || contains(github.event.commits[0].added, 'api/') || contains(github.event.commits[0].removed, 'api/')) || (github.event_name == 'pull_request' && contains(github.event.pull_request.files, 'api/'))
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Common steps
        id: common-steps
        uses: ./.github/actions/common-steps
        with:
          context: ./blog
          image_name: ${{ env.IMAGE_NAME }}-api
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug tags output
        run: |
          echo "Tags: ${{ steps.common-steps.outputs.tags }}"

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./api
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.common-steps.outputs.tags }}
          platforms: linux/arm64,linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.common-steps.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}