name: Publish Api

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
    paths:
      - 'api/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'api/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-api:
    strategy:
      matrix:
        config:
          - platform: linux/amd64
            runs_on: ubuntu-latest
          - platform: linux/arm64
            runs_on: buildjet-2vcpu-ubuntu-2204-arm

    runs-on: ${{ matrix.config.runs_on }}
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Set up job
        run: echo "Running on ${{ matrix.config.runs_on }} for Docker platform ${{ matrix.config.platform }}"
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Common steps
        id: common-steps
        uses: ./.github/actions/common-steps
        with:
          context: ./api
          image_name: ${{ env.IMAGE_NAME }}-api
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug tags output
        run: |
          echo "Tags: ${{ steps.common-steps.outputs.tags }}"

      - name: Decode certificate from Base64
        run: |
          cd ./api
          echo "${{ secrets.CERTIFICATE_PFX_BASE64 }}" | base64 --decode > certificate.pfx
        
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6.0.0
        with:
          context: ./api
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.common-steps.outputs.tags }}
          platforms: ${{ matrix.config.platform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.common-steps.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
