name: Publish Portfolio

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
    paths:
      - 'portfolio/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'portfolio/**'
  workflow_dispatch:
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-portfolio:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js for React frontend
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Build and Test React frontend
      - name: Install React Dependencies (Frontend)
        working-directory: .
        run: npm install
      - name: Build React (Frontend)
        working-directory: .
        run: npm run build
      - name: Test React (Frontend)
        working-directory: .
        run: npm test -- --watchAll=false

      # Step 4: Set up Java for Quarkus backend
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Step 5: Grant execute permission for mvnw
      - name: Grant execute permission for mvnw
        working-directory: .
        run: chmod +x ./mvnw

      # Step 6: Build Quarkus backend
      - name: Build Quarkus Application
        working-directory: .
        run: ./mvnw package -DskipTests

      # Step 7: Test Quarkus backend
      - name: Test Quarkus (Backend)
        working-directory: .
        run: ./mvnw test

      # Step 8: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: network=host
          buildkitd-flags: --allow-insecure-entitlement security.insecure

      # Step 9: Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 10: Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./com.rubenflinterman
          file: ./com.rubenflinterman/src/main/docker/Dockerfile.jvm
          platforms: linux/arm64/v8,linux/amd64
          push: true
          tags: |
            ghcr.io/RFlintstone/rubenflinterman.com:latest
            ghcr.io/RFlintstone/rubenflinterman.com:${{ github.sha }}

      # Step 11: Post Status Check (Optional)
      - name: Build Summary
        run: echo "Docker image build and push completed successfully!"
